version: '3.6'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elastic/elasticsearch:7.4.2
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'

  kibana:
    container_name: kibana
    image: elastic/kibana:7.4.2
    restart: always
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    build: ./logstash
    restart: always
    ports:
      - '9600:9600'
    depends_on:
      - elasticsearch

  # Nginx Server For Frontend App
  nginx:
    container_name: nginx
    image: nginx
    volumes: # Serve local 'app' dir
      - ./app:/usr/share/nginx/html
    ports:
      - '80:80' # Forward site to localhost:80

  # Node.js API
  api:
    container_name: api
    build: ./api
    ports:
      - '3000:3000' # Expose API port
    environment: # Set ENV vars
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - PORT=3000

  # DB
  db:
    container_name: db
    build: ./db
    restart: always

  # Adminer
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'
