version: '3.6'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elastic/elasticsearch:7.4.2
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'

  kibana:
    container_name: kibana
    image: elastic/kibana:7.4.2
    restart: always
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  # logstash:
  #   container_name: logstash
  #   build: ./logstash
  #   restart: always
  #   depends_on:
  #     - elasticsearch

  # Nginx Server For Frontend App
  nginx:
    container_name: nginx
    image: nginx
    volumes: # Serve local 'app' dir
      - ./app:/usr/share/nginx/html
    ports:
      - '80:80' # Forward site to localhost:80

  api: # Node.js App
    container_name: api
    build: ./api
    ports:
      - '3000:3000' # Expose API port
      # - '9229:9229' # Expose Node process debug port (disable in production)
    environment: # Set ENV vars
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - PORT=3000

  db:
    container_name: db
    # image: mysql:8.0.18
    # image: mariadb:10.4.10-bionic
    build: ./db
    restart: always
    # environment:
    # MYSQL_ROOT_PASSWORD: password
    # MYSQL_DATABASE: copenhagen
    # MYSQL_USER: app
    # MYSQL_PASSWORD: secret
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'
